# Prometheus configuration for Rotonda monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Rotonda metrics
  - job_name: 'rotonda'
    static_configs:
      - targets: ['rotonda:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Optional: MQTT broker metrics (if mosquitto_exporter is used)
  # - job_name: 'mqtt-broker'
  #   static_configs:
  #     - targets: ['mqtt-exporter:9234']